###
POST http://localhost:8080/swabTestDetails/abc@gmail.com
Content-Type: application/json

{
    
    "alertDay": "MON",
    "alertTime": "11:22",
    "message" : "hghhhhhh"
}

###
GET http://localhost:8080/swabTestDetails/abc@gmail.com

###
PUT http://localhost:8080/users/abc@gmail.com/swabTestDetails/1
Content-Type: application/json

{
    "alertTime": "00:00",
    "alertDay":"SUN",
    "message": "hghgh"
}

# cannot do put without the alertDay--not sure why?

###
DELETE http://localhost:8080/users/abc@gmail.com/swabTestDetails/2