# get swab tests
###
GET http://localhost:8080/swabTests/regina.chua.2020@smu.edu.sg
Accept: application/json
Authorization: Basic regina.chua.2020@smu.edu.sg password123

# get specific swab Test according to swabResult and date
###
GET http://localhost:8080/swabTests/false/2020-09-09
//Accept: application/json
###
GET http://localhost:8080/swabTests/2020-09-01/date/2020-09-20

# get individual swab results (user)
###
GET http://localhost:8080/users/def@gmail.com/swabTests
Accept: application/json

#add swab result
###
POST http://localhost:8080/users/def@gmail.com/swabTests
Content-Type: application/json

{
    "swabResult": "false",
    "actualSwabDate": "2021-10-10"
}
###
PUT http://localhost:8080/users/def@gmail.com/swabTests/1
Content-Type: application/json

{
    "actualSwabDate": "2020-09-01"
}