# add company
###
POST http://localhost:8080/companies/industry1/addCompany
Content-Type: application/json

{
    "name": "company a"
}

# add company to same industry
###
POST http://localhost:8080/companies/industry1/addCompany
Content-Type: application/json

{
    "name": "company b"
}

# add company to another industry
###
POST http://localhost:8080/companies/industry2/addCompany
Content-Type: application/json

{
    "name": "company c"
}

# get companies
### 
GET http://localhost:8080/companies
Accept: application/json

# get company by id
### 
GET http://localhost:8080/companies/1
Accept: application/json

#update company
###
PUT http://localhost:8080/companies/1
Content-Type: application/json

{
    "name": "company d"
}


#add event
###
POST http://localhost:8080/companies/2/events
Content-Type: application/json

{
    "event": "Company Dinner",
    "eventDate": "12-10-21",
    "location": "Dhoby Ghaut"
}

# add user: admin
###
POST http://localhost:8080/users/admin/registration
Content-Type: application/json

{
    "companyId": "1",
    "email": "abc@gmail.com",
    "name": "admin a",
    "password": "goodpassword123",
    "role": "HR"
}

# add user: employee - company doesnt exist
###
POST http://localhost:8080/users/2
Content-Type: application/json
Authorization: Basic abc@gmail.com goodpassword123

{
    "email": "hij@gmail.com",
    "name": "employee c",
    "password": "goodpassword",
    "role": "tester",
    "authorities": "ROLE_USER"
}


# delete company
###
DELETE http://localhost:8080/companies/1
Content-Type: application/json
Authorization: Basic abc@gmail.com goodpassword




