# get users
GET http://localhost:8080/users
Accept: application/json

# add user: admin
###
POST http://localhost:8080/users/1
Content-Type: application/json

{
    "email": "abc@gmail.com",
    "name": "admin a",
    "password": "goodpassword",
    "role": "HR",
    "authorities": "ROLE_ADMIN"
}

# add user: employee - company doesnt exist
###
POST http://localhost:8080/users/2
Content-Type: application/json

{
    "email": "hij@gmail.com",
    "name": "employee c",
    "password": "goodpassword",
    "role": "tester",
    "authorities": "ROLE_USER"
}

# add user: employee
###
POST http://localhost:8080/users/1
Content-Type: application/json
Authorization: Basic abc@gmail.com goodpassword

{
    "email": "def@gmail.com",
    "name": "employee b",
    "password": "goodpassword",
    "role": "developer",
    "authorities": "ROLE_USER"
}

# get users: by company id
###
GET http://localhost:8080/users/1
Accept: application/json

# reset user password
###
PUT http://localhost:8080/users/1/abc@gmail.com/resetPassword
Authorization: Basic abc@gmail.com goodpassword

# change user password
###
PUT http://localhost:8080/users/1/abc@gmail.com/changePassword
Content-Type: application/json
Authorization: Basic abc@gmail.com goodpassword

{
    "currentPassword": "goodpassword",
    "newPassword": "abcd123@"
}

# delete users: by user email and company id
###
DELETE http://localhost:8080/users/1/def@gmail.com