###
POST http://localhost:8080/swabTestDetails/abc123@gmail.com
Content-Type: application/json

{
    
    "alertDay": "MON",
    "alertTime": "11:22",
    "message" : ""
}

###
GET http://localhost:8080/localhost:8080/swabTestDetails/abc123@gmail.com