# add feedback
###
POST http://localhost:8080/users/abc@gmail.com/feedbacks
Content-Type: application/json
Authorization: Basic abc@gmail.com goodpassword123

{
    "title": "feedback2",
    "details": "details for feedback2"
}