
#get events 
###
GET http://localhost:8080/companies/2/events

#get event users 
###

GET http://localhost:8080/users/1/8

#get user past events 
###

GET http://localhost:8080/users/sarahanngwps@gmail.com/2/events


#get user events 
###

GET http://localhost:8080/users/sarahanngwps@gmail.com/events

#get user upcoming events 
###

GET http://localhost:8080/users/sarahanngwps@gmail.com/companies/events

#get event status 
###
GET http://localhost:8080/swabTests/users/2/23

#get location status 
###
GET http://localhost:8080/swabTests/events/2/23

#get user non-registered events 
###

GET http://localhost:8080/companies/1/events/test1@gmail.com

#get events with users who tested positive 
###

GET http://localhost:8080/swabTests/events/1


#add event
###
POST http://localhost:8080/users/sarahanngwps@gmail.com/companies/2/events
Content-Type: application/json

{
    "event": "Birthday",
    "eventDate": "05/09/2021",
    "location": "Carlton Hotel"
}

#add users to the event
###
PUT http://localhost:8080/companies/2/events/48/users/claire@gmail.com


#delete users from the event 
###

PUT http://localhost:8080/events/1/16/users/test1@gmail.com


#update event 
###
PUT http://localhost:8080/companies/1/events/1
Content-Type: application/json

{
    "event": "Project Meeting",
    "eventDate": "30-12-21",
    "location": "Jurong East"
}

#delete event 
###
DELETE http://localhost:8080/companies/2/events/21