# get users
GET http://localhost:8080/users
Accept: application/json

# add user: admin
###
POST http://localhost:8080/users/1
Content-Type: application/json

{
    "email": "abc@gmail.com",
    "name": "admin a",
    "password": "goodpassword",
    "role": "HR",
    "authorities": "ROLE_ADMIN"
}

# add user: employee - company doesnt exist
###
POST http://localhost:8080/users/2
Content-Type: application/json

{
    "email": "hij@gmail.com",
    "name": "employee c",
    "password": "goodpassword",
    "role": "tester",
    "authorities": "ROLE_USER"
}

# add user: employee
###
POST http://localhost:8080/users/1
Content-Type: application/json
Authorization: Basic abc@gmail.com goodpassword

{
    "email": "def@gmail.com",
    "name": "employee b",
    "password": "goodpassword",
    "role": "developer",
    "authorities": "ROLE_USER"
}